Task/Task/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^scheduler/',include('scheduler.urls')),
    #url(r'^',include('scheduler.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Task/scheduler/urls.py
from django.conf.urls import url
from django.urls import path
from .views import IndexView,AddTask,UserFormView,TaskDelete,DetailView,TaskUpdate
from django.contrib.auth import views as auth_views

app_name = 'sdlrs'

urlpatterns = [
    # /scheduler/
    url(r'^$',IndexView.as_view(), name='index'),
    url(r'^add/$',AddTask.as_view(),name='task-add'),
    url(r'^register/$',UserFormView.as_view(), name='register'),
    #/scheduler/sch_id
    url(r'detail/(?P<pk>[0-9]+)/$', TaskUpdate.as_view(), name='task-update'),
    url(r'detail/(?P<pk>[0-9]+)/$',DetailView.as_view(),name='detail'),

    url(r'^(?P<pk>[0-9]+)/delete/$',TaskDelete.as_view(), name='task-delete'),
    url(r'^login/$',auth_views.LoginView.as_view(),{'template_name':'scheduler/login.html'},name='login'),
    url(r'^logout/$',auth_views.LogoutView.as_view(),{'template_name':'scheduler/logout.html'},name='logout'),
    #url(r'^register/$',views.UserFormView.as_view(), name='register'),
]

Task/scheduler/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Q

class TaskManager(models.Model):
    task = models.CharField(max_length=1000)
    t_Creator = models.CharField(max_length=250)
    t_Assigned = models.CharField(max_length=250)
    t_Done = models.BooleanField(default=False)

    def get_absoulte_url(self):
        return reverse('sdlrs:detail', kwargs={'pk': self.pk})

Task/scheduler/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
         model= User
         fields = ['username','email','password']

Task/scheduler/views.py
from django.views import generic
from .models import TaskManager
from .forms import UserForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from django.views.generic import View, ListView
from django.contrib.auth.models import User

class IndexView(generic.ListView):
    template_name = 'scheduler/index.html'
    model = TaskManager

    def IndexView(request):
        args={'user',request.user}
        return render(request,'scheduler/index.html',args)

class AddTask(CreateView):
    model=TaskManager
  #  template_name = 'scheduler/taskmanager_form.html'
    fields=['task','t_Creator','t_Assigned','t_Done']
    success_url = reverse_lazy('sdlrs:index')

class UserFormView(View):
    form_class=UserForm
    template_name='scheduler/registration_form.html'

    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user=form.save(commit=False)

            #Clean Data

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user=authenticate(username=username,password=password)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('sdlrs:index')

        return render(request, self.template_name, {'form': form})

class DetailView(generic.DetailView):
    model = TaskManager
    template_name = 'scheduler/detail.html'

class TaskDelete(DeleteView):
    model=TaskManager
    success_url = reverse_lazy('sdlrs:index')

class TaskUpdate(UpdateView):
    model=TaskManager
    fields=['task','t_Creator','t_Assigned','t_Done']
    success_url = reverse_lazy('sdlrs:index')

def post_list(request):
    posts = TaskManager.objects.all()
    query = request.GET.get('q')
    query = TaskManager.objects.filter(title__icontains=query)
    context={
        'post' : posts,
    }
    return render(request,'scheduler/index.html',context)

Task/scheduler/templates/scheduler/TaskManager_form.html
{% extends 'scheduler/base.html' %}
{% block title %} New Task {% endblock %}
{% block albums_active %} active {% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'scheduler/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Task/scheduler/templates/scheduler/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Scheduler{% endblock %}</title>
    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'sch/style.css' %}" />
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">

    <div class ="container-fluid">
        <!-- header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'sdlrs:index' %}">Scheduler</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

           <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" placeholder="Search Tasks">
                    <button type="submit" class="btn btn-default">Search</button>
                </div>
           </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'sdlrs:task-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Task
                    </a>
                </li>

                <li class="">
                    <a href="{% url 'sdlrs:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; LogOut
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Task/scheduler/templates/scheduler/detail.html
{% extends 'scheduler/base.html' %}
{% block title %}Task Details{% endblock %}
{% block body %}

<div class="container-fluid">

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <a href="{% url 'sdlrs:task-update' publisher.id%}">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Edit Task
    </a>
</div>
{% endblock %}

Task/scheduler/templates/scheduler/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

Task/scheduler/templates/scheduler/index.html
{% extends 'scheduler/base.html' %}

{% block body %}
    <div class="container">
        {% if user.is_authenticated %}
            <h1>Welcome {{ user }},</h1><br/>
            <h2>Task Schedule</h2>
            <table class="table">
                <thead>
                <tr>
                    <th>Task</th>
                    <th>Assignee</th>
                    <th>Assigned</th>
                    <th>Done</th>
                </tr>
                </thead>
                <tbody>
                {% for publisher in object_list %}

                    <tr>
                        <td><a href="{% url 'sdlrs:detail' publisher.id %}">{{ publisher.task }}</a></td>
                        <td>
                              {% ifequal user.username publisher.t_Creator %}
                            <form action="{% url 'sdlrs:task-delete' publisher.id %}" method="post" style="display : inline;">
                                {% csrf_token %}
                                <input type="hidden" name="publisher_id" value="{{ publisher.id }}"/>
                                    <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                            {% endifequal %}
                            {{ publisher.t_Creator }}
                        </td>

                        <td>{{ publisher.t_Assigned }}</td>

                        <td>
                            {{ publisher.t_Done }}
                        </td>
                    </tr>

                {% endfor %}
                </tbody>
            </table>
            </div>
        {% else %}
            <h3>Oops!!! Looks like you forgot to Log In. Please, <a href="{% url 'sdlrs:login' %}">click here</a> to log in...</h3>
        {% endif  %}



{% endblock %}

Task/scheduler/templates/scheduler/login.html
{% extends 'scheduler/base.html' %}
{% block title %}LogIn{% endblock %}


{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Log In</h3>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'scheduler/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Log In</button>
                                </div>
                            </div>
                        </form>
                        <a href="{% url 'sdlrs:register' %}">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp;<b>Register Me!!</b>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Task/scheduler/templates/scheduler/logout.html
{% extends 'scheduler/base.html' %}
{% block title %}LogOut{% endblock %}


{% block body %}

    <div class="container-fluid">
        <h1>You have been successfully logged out!!!</h1>
        <h3>Please <a href="{% url 'sdlrs:login' %}">click here</a> to log in again...</h3>
    </div>

{% endblock %}

Task/scheduler/templates/scheduler/registration_form.html
{% extends 'scheduler/base.html' %}
{% block title %}Register{% endblock %}


{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Create a New Account</h3>
                        {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'scheduler/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}